services:
      dufa_core_manager.user:
          class: Dufa\Bundle\CoreBundle\Manager\User
          arguments:
              - "@doctrine.orm.entity_manager"
              - Dufa\Bundle\CoreBundle\Entity\User
              - "@security.encoder_factory"

      dufa_core_manager.ask_questions:
          class: Dufa\Bundle\CoreBundle\Manager\AskQuestions
          arguments:
              - "@doctrine.orm.entity_manager"
              - Dufa\Bundle\CoreBundle\Entity\AskQuestions

      dufa_core_manager.goods:
          class: Dufa\Bundle\CoreBundle\Manager\Goods
          arguments:
              - "@doctrine.orm.entity_manager"
              - Dufa\Bundle\CoreBundle\Entity\Goods

      dufa_core_manager.useraddress:
          class: Dufa\Bundle\CoreBundle\Manager\UserAddress
          arguments:
              - "@doctrine.orm.entity_manager"
              - Dufa\Bundle\CoreBundle\Entity\UserAddress

      dufa_core_manager.orders:
          class: Dufa\Bundle\CoreBundle\Manager\Orders
          arguments:
              - "@doctrine.orm.entity_manager"
              - Dufa\Bundle\CoreBundle\Entity\Orders

      dufa_core_manager.experts:
          class: Dufa\Bundle\CoreBundle\Manager\Experts
          arguments:
              - "@doctrine.orm.entity_manager"
              - Dufa\Bundle\CoreBundle\Entity\Experts