<?php

namespace Dufa\Bundle\CoreBundle\Repository;

/**
 * AskQuestions
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AskQuestions extends \Doctrine\ORM\EntityRepository
{
}
