<?php

namespace Dufa\Bundle\CoreBundle\Repository;

/**
 * Comments
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Comments extends \Doctrine\ORM\EntityRepository
{
}
