<?php

namespace Dufa\Bundle\CoreBundle\Repository;

/**
 * Role
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Role extends \Doctrine\ORM\EntityRepository
{
}
