<?php

namespace Dufa\Bundle\CoreBundle\Repository;

/**
 * UserAccountRecord
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAccountRecord extends \Doctrine\ORM\EntityRepository
{
}
