dufa_api_news:
    resource: "@DufaApiBundle/Resources/config/routing/news.yml"
    prefix:   /news

dufa_api_statistical:
    resource: "@DufaApiBundle/Resources/config/routing/statistical.yml"
    prefix:   /statistical

dufa_api_dictionay:
    resource: "@DufaApiBundle/Resources/config/routing/dictionay.yml"
    prefix:   /dictionay

dufa_api_register:
    resource: "@DufaApiBundle/Resources/config/routing/register.yml"
    prefix:   /user/register

dufa_api_userrecord:
    resource: "@DufaApiBundle/Resources/config/routing/user_record.yml"
    prefix:   /user/record

dufa_api_useraddress:
    resource: "@DufaApiBundle/Resources/config/routing/user_address.yml"
    prefix:   /user/address

dufa_api_ask_questions:
    resource: "@DufaApiBundle/Resources/config/routing/ask_questions.yml"
    prefix:   /ask/questions

dufa_api_ask_questions_answer:
    resource: "@DufaApiBundle/Resources/config/routing/ask_questions_answer.yml"
    prefix:   /ask/questions

dufa_api_user_operate:
    resource: "@DufaApiBundle/Resources/config/routing/user_operate.yml"
    prefix:   /user/operate

dufa_api_goods:
    resource: "@DufaApiBundle/Resources/config/routing/goods.yml"
    prefix:   /shopping/goods

dufa_api_orders:
    resource: "@DufaApiBundle/Resources/config/routing/orders.yml"
    prefix:   /shopping/orders

dufa_api_login:
    path:     /login
    defaults: { _controller: DufaApiBundle:V1/Security:login }

dufa_api_logout:
    path:     /logout
    defaults: { _controller: DufaApiBundle:V1/Security:logout }

dufa_api_getuser:
    path:     /getuser
    defaults: { _controller: DufaApiBundle:V1/Security:getUser }

dufa_api_sendcode:
    path:     /sendcode
    defaults: { _controller: DufaApiBundle:V1/Security:sendcode }

dufa_api_reset:
    path:     /reset-password
    defaults: { _controller: DufaApiBundle:V1/Resetting:reset }
    methods: post