dufa_user:
    resource: "@DufaUserBundle/Resources/config/routing.yml"
    prefix:   /

dufa_web:
    resource: "@DufaWebBundle/Resources/config/routing.yml"
    prefix:   /

dufa_core:
    resource: "@DufaCoreBundle/Resources/config/routing.yml"
    prefix:   /

dufa_api:
    resource: "@DufaApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc