backend_orders_list:
    path:     /list
    defaults: { _controller: DufaWebBundle:Backend\Orders:list }

backend_orders_new:
    path:     /new
    defaults: { _controller: DufaWebBundle:Backend\Orders:new }

backend_orders_edit:
    path:     /{id}/edit
    defaults: { _controller: DufaWebBundle:Backend\Orders:edit,id: 0 }

backend_orders_del:
    path:     /{id}/del
    defaults: { _controller: DufaWebBundle:Backend\Orders:del,id: 0 }