services:
      dufa_user_manager.user:
          class: Dufa\Bundle\UserBundle\Manager\UserManager
          arguments:
              - "@doctrine.orm.entity_manager"
              - Dufa\Bundle\UserBundle\Entity\User
              - "@security.encoder_factory"


      dufa_user_manager.role:
          class: Dufa\Bundle\UserBundle\Manager\RoleManager
          arguments:
              - "@doctrine.orm.entity_manager"
              - Dufa\Bundle\UserBundle\Entity\Role

      dufa_user_manager.userprofile:
          class: Dufa\Bundle\UserBundle\Manager\UserProfileManager
          arguments:
              - "@doctrine.orm.entity_manager"
              - Dufa\Bundle\UserBundle\Entity\UserProfile
