web_backend:
    resource: "@DufaWebBundle/Resources/config/routing/backend.yml"
    prefix:   /admin

web_frontend:
    resource: "@DufaWebBundle/Resources/config/routing/frontend.yml"
    prefix:   /