dufa_user_registration_register:
    path:     /register
    defaults: { _controller: DufaUserBundle:Registration:register }

dufa_user_registration_checkemail:
    path:     /check-email
    defaults: { _controller: DufaUserBundle:Registration:checkEmail }

dufa_user_registration_confirm:
    path:     /confirm/{token}
    defaults: { _controller: DufaUserBundle:Registration:confirm }

dufa_user_registration_confirmed:
    path:     /confirmed
    defaults: { _controller: DufaUserBundle:Registration:confirmed }

dufa_user_registration_active:
    path:     /active
    defaults: { _controller: DufaUserBundle:Registration:active }

