backend_index_index:
    path:     /
    defaults: { _controller: DufaWebBundle:Backend\Index:index }

backend_index_welcome:
    path:     /welcome
    defaults: { _controller: DufaWebBundle:Backend\Index:welcome }

web_backend_useroperaterecord:
    resource: "@DufaWebBundle/Resources/config/routing/backend/user_operate_record.yml"
    prefix:   /user/operate-record