<?php

namespace Appcoachs\Bundle\UserBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ModulesRepository.
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ModulesRepository extends DocumentRepository
{
    public function getModuleList($condition = array())
    {
        $qb = $this->createQueryBuilder('m');
        $condition['isDelete'] = isset($condition['isDelete']) ? $condition['isDelete'] : false;
        $condition['isEnable'] = isset($condition['isEnable']) ? $condition['isEnable'] : true;
        $this->_getWhere($qb, $condition);
        $result = $qb->getQuery()->toArray();

        return $result;
    }

    /**
     * @author  gf
     *
     * 生成查询条件
     *
     * @param $qb
     * @param array $condition
     *
     * @return mixed
     */
    private function _getWhere($qb, $condition = array())
    {
        if (!empty($condition)) {
            if (isset($condition['pId']) && !empty($condition['pId'])) {
                $qb->field('pId')->equals($condition['pId']);
            }

            if (isset($condition['isDelete'])) {
                $qb->field('isDelete')->equals($condition['isDelete']);
            }

            if (isset($condition['isEnable'])) {
                $qb->field('isEnable')->equals($condition['isEnable']);
            }
        }

        return $qb;
    }
}
