<?php

namespace Appcoachs\Bundle\UserBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ModulePermissionsRepository.
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class ModulePermissionsRepository extends DocumentRepository
{
}
