<?php

namespace Appcoachs\Bundle\UserBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * RolePermissionsRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class RolePermissionsRepository extends DocumentRepository
{

}
