<?php

namespace Appcoachs\Bundle\UserBundle\Document\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
    public function getUserList($condition = array(), $offset = 0, $limit = 100)
    {
        $db = $this->createQueryBuilder('u');
        $this->_getWhere($db, $condition);
        $db->skip($offset);
        $db->limit($limit);
        $db->sort('createdAt', -1);
        $result = $db->getQuery()->execute();
        return !empty($result) ? $result : array();
    }

    /**
     * @author  gf
     *
     * 生成查询条件
     *
     * @param $db
     * @param array $condition
     *
     * @return mixed
     */
    private function _getWhere($db, $condition = array())
    {
        if (!empty($condition)) {
            foreach ($condition as $k => $v) {
                if (isset($k) && !empty($k) && isset($v) && !empty($v)) {
                    $param = explode('_', $k);
                    switch ($param[1]) {
                        case 'like':
                            dump($param);exit;
                            $db->field($param[0])->equals(new \MongoRegex('/.*'.$v.'.*/i'));
                            break;
                        case 'equal':
                            $db->field($param[0])->equals($v);
                            break;
                    }
                }
            }
        }

        return $db;
    }
}
