api_dictionay_list:
    path:     /list
    defaults: { _controller: DufaApiBundle:V1/Dictionay:list }

api_dictionay_details:
    path:     /{id}/details
    defaults: { _controller: DufaApiBundle:V1/Dictionay:details, id: 0 }