api_news_list:
    path:     /{cId}/list
    defaults: { _controller: DufaApiBundle:V1/News:list,cId: 0 }
    methods: get

api_news_details:
    path:     /{id}/details
    defaults: { _controller: DufaApiBundle:V1/News:details, id: 0 }
    methods: get
