api_orders_list:
    path:     /list
    defaults: { _controller: DufaApiBundle:V1/Orders:list }
    methods: post

api_orders_details:
    path:     /{id}/details
    defaults: { _controller: DufaApiBundle:V1/Orders:details,id: 0 }
    methods: post

api_orders_createorder:
    path:     /{goodsId}/{addressId}/create
    defaults: { _controller: DufaApiBundle:V1/Orders:createOrder,goodsId: 0,addressId: 0 }
    methods: post
