api_user_address_list:
    path:     /list
    defaults: { _controller: DufaApiBundle:V1/UserAddress:list }
    methods: get

api_user_address_new:
    path:     /new
    defaults: { _controller: DufaApiBundle:V1/UserAddress:new }
    methods: post

api_user_address_edit:
    path:     /{id}/edit
    defaults: { _controller: DufaApiBundle:V1/UserAddress:edit,id: 0 }
    methods: post

api_user_address_delete:
    path:     /{id}/delete
    defaults: { _controller: DufaApiBundle:V1/UserAddress:delete, id: 0 }
    methods: get
